language: objective-c
osx_image: xcode11.3
cache:
  - bundler
  - cocoapods
before_install:
  - export LANG=en_US.UTF-8
  - gem install bundler -v 2.0.2
script:
  - bundle exec rake build
  - bundle exec rake test
notifications:
  email: false
