name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: rake install and test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - name: Run bundle install
        run: |
          gem list bundler
          bundle install

      - name: Build app
        run: |
          bundle exec rake build

      - name: Run tests
        run: |
          bundle exec rake test
